### PR TITLE
fix(PageToggle): resolved sidebar not collapsing correctly

### LINKED ISSUE #26: Bug - Sidebar content disappears
On my local build, when I click the hamburger icon button to collapse the sidebar, the sidebar stays open while the content disappears. If I click the button again the sidebar collapses as expected, but when trying to open the sidebar the content no longer renders.

### PR DESCRIPTION
**Pull request by thatblindgeye**
Closes #26

### CODE REVIEW

**Review by wise-king-sullyman — APPROVED** [review]

**Review by mfrances17 — APPROVED** [review]

**Review by dlabaj — APPROVED** [review]

**Comment by thatblindgeye** [comment]
FYI I'm going to push an update for the alternative method that we had gone over last Friday. Per Coker that alternative method would be the more correct way -- we can tweak things further as a followup once https://github.com/patternfly/patternfly/issues/7377 goes in (this core work would mean not having to apply the classes on the astro island and just having PageSidebar as a child of that island)

File: src/components/PageToggle.tsx [hunk 1]
```diff
@@ -11,20 +11,26 @@ export const PageToggle: React.FunctionComponent = () => {
...
 
     if (!isClientSide || !sideBarIsland) {
       return
     }
 
     if (!sideBarIsland.classList.contains('pf-v6-c-page__sidebar')) {
-      sideBarIsland.classList.add('pf-v6-c-page__sidebar', 'pf-m-expanded')
+      sideBarIsland.classList.add(
+        'pf-v6-c-page__sidebar',
+        $isNavOpen ? 'pf-m-expanded' : 'pf-m-collapsed',
```
Comment (mcoker) [inline src/components/PageToggle.tsx:27]: 👍

**Review by mcoker — APPROVED** [review]
LGTM!

Not a blocker or anything but the hard-coded classes will need manual updates with new PF versions (`pf-v6-...` to `pf-v7-...`). At least for those (and probably the modifiers, too, but not as big of a deal) I wonder if we should import `'@patternfly/react-styles/css/components/Page/page'` so we can use `styles.pageSidebar` instead of `pf-v6-c-page__sidebar`

**Review by dlabaj — CHANGES_REQUESTED** [review]
Looks like there's a warning for applySidebarStylesToIsland in the hook.

File: src/components/PageToggle.tsx [hunk 2]
```diff
@@ -33,13 +40,13 @@ export const PageToggle: React.FunctionComponent = () => {
 
   useEffect(() => {
     applySidebarStylesToIsland()
-  }, [$isNavOpen])
+  }, [$isNavOpen, applySidebarStylesToIsland])
```
Comment (wise-king-sullyman) [inline src/components/PageToggle.tsx:43]: I think that if you're putting a function into the hook deps you need to wrap it in `useCallback` to prevent constant rerenders no?

Comment (thatblindgeye) [reply src/components/PageToggle.tsx:43]: Ah fair, could also just move the function inside the hook instead, I don't foresee it ever being used outside of it.

File: src/components/PageToggle.tsx [hunk 3]
```diff
@@ -9,38 +9,38 @@ import { useEffect } from 'react'
...
+          $isNavOpen ? styles.modifiers.expanded : styles.modifiers.collapsed,
+        )
+      } else {
+        sideBarIsland.classList.toggle(styles.modifiers.expanded)
+        sideBarIsland.classList.toggle(styles.modifiers.collapsed)
+      }
+      sideBarIsland.setAttribute('aria-hidden', `${!$isNavOpen}`)
+    }
+
     applySidebarStylesToIsland()
```
Comment (wise-king-sullyman) [inline src/components/PageToggle.tsx:42]: 🤔 is there even much reason to wrap all this in a function and effectively use it as a named IIFE? Seems like we could just have this logic straight in the effect

**Review by wise-king-sullyman — APPROVED** [review]
🚀 
🔥
