### PR TITLE
fix(cli): support monorepos

### LINKED ISSUE #118: Monorepos are not properly supported
When attempting to have the docs core render docs from packages it looks in the `node_modules` directory at the same level as the docs cli call site, which is not compatible with monorepos such as org where the main `node_modules` lives at the top of the repo but build/start/etc scripts are called from a package inside the monorepo

Additionally the internal mdx conversion is not functioning in monorepos.

### PR DESCRIPTION
**Pull request by wise-king-sullyman**
Closes #118

Also expands verbose mode logging a good bit since it became evident that we didn't have enough to really help with debugging.

Assisted-by: Cursor running claude-4-sonnet

### CODE REVIEW

File: cli/buildPropsData.ts [hunk 1]
```diff
@@ -88,8 +88,17 @@ export async function buildPropsData(
   configFile: string,
   verbose: boolean,
 ) {
+  const verboseModeLog = (...messages: any) => {
+    if (verbose) {
+      console.log(...messages)
+    }
+  }
+
+  verboseModeLog('Begging props data build')
```
Comment (dlabaj) [inline cli/buildPropsData.ts:97]: Is this supposed to be beginning?

**Review by dlabaj — APPROVED** [review]
Just one small comment. Otherwise LGTM.

File: cli/buildPropsData.ts (hunk 1 above)
Comment (wise-king-sullyman) [reply cli/buildPropsData.ts:97]: Whoops yeah, this is why I write code not English 😆

**Review by kmcfaul — APPROVED** [review]
